#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Agent fallback: project multi-matched compose + node-express catalog entries
#     (docker-compose.yml + package.json with express). Compose is the canonical
#     runtime: it orchestrates db (postgres:16), db-migrate (health-gated), db-seed,
#     api (Express/Node), and frontend (React/Vite). `docker compose up --build` is
#     the single exec command (single-process wrapper: compose handles multi-service
#     orchestration). The multi-process template is NOT used — compose is a single
#     foreground process from the wrapper's perspective (multi-process-template.md §6).
#   - Stale-volume guard: this compose stack uses docker-entrypoint-initdb.d for
#     schema init (db/migrations/ mounted read-only). initdb.d scripts ONLY run on
#     a FRESH postgres volume. On a pre-existing postgres_data volume the migrations
#     are NOT re-applied, so db-migrate / db-seed services would fail silently and
#     the app would boot onto an empty/wrong DB schema. `docker compose down -v`
#     before up drops the volume so the init path always runs cleanly.
#     This is idempotent: `down -v` is a no-op on a fresh sandbox with no prior volume.
#   - Retry loop: 3 attempts, 1s/2s/4s backoff (D-14). Compose is a single foreground
#     command so the single-process retry loop applies.
#   - Port 3000 (frontend/Vite) is the primary ready port; 3001 (API) is secondary.
#     Both are published to 0.0.0.0 via docker-compose.yml `ports:` mapping.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
# Multiple platform paths can invoke the wrapper concurrently (sandbox setup,
# preview open, verify pre-flight) — observed as two `docker compose up --build`
# trees racing in one sandbox. Second invocation exits 0 quietly: the first
# boot is authoritative and callers poll the port, not this process.
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
# Researcher resolved log destination: /tmp/pivota-dev.log (always writable,
# matches existing convention). SSE chat panel sees output live AND a file
# exists for scrollback / replay.
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === D-11.1 + D-11.2: Compose controls service bind addresses ===
# Both api (3001) and frontend (3000) are published via `ports:` in docker-compose.yml
# which binds them to 0.0.0.0 on the sandbox host. No env-var lever needed in the
# wrapper — compose port mappings already satisfy the 0.0.0.0 binding requirement.
# DO NOT set NODE_ENV=production here — it would strip devDependency build toolchain.

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Seed .env from .env.example for first boot, but NEVER let an .env.example
# placeholder shadow a variable the platform already injected into the sandbox
# environment. Any KEY already set in the environment is dropped from the copy
# so the injected value wins. See references/runtime-environment.md §3.
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    # D-11.5: strip inline comments from unquoted values
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    # Replace CHANGE_ME placeholder secrets with generated values
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === Stale-volume guard ===
# postgres_data is a named docker volume. docker-entrypoint-initdb.d scripts
# (db/migrations/ mounted at /docker-entrypoint-initdb.d) ONLY execute on a
# FRESH, empty volume. On a pre-existing volume (any prior sandbox boot) the
# init scripts are skipped — leaving the DB in whatever state the prior boot
# left it. This is unsafe for a dev environment where schema is source-of-truth.
# Drop the volume + any orphaned containers before each boot so init always runs.
# `--remove-orphans` cleans up containers from removed services.
echo "[pivota] stopping any prior compose stack (volumes + orphans) for idempotent schema init"
docker compose down -v --remove-orphans 2>&1 || true

# === D-12: No lockfile/install step for a compose stack ===
# `docker compose up --build` manages image layers via Docker's build cache.
# Dockerfiles handle all installs inside image builds. No npm ci/lockfile
# sentinel needed in the wrapper.

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
# Final-attempt exit code propagates the INNER command's exit code, not a
# fixed 1, so the caller (platform / Daytona) can distinguish "wrapper bug"
# from "user command failed with N".
# NOTE: on retry, truncate the log so Gate 3 only sees the LAST attempt's
# output — a transient container-name conflict on attempt 1 should not leave
# stale ERROR lines that false-fail the boot-smoke.
EXEC_CMD='docker compose up --build'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  if (( ATTEMPT > 1 )); then
    echo "[pivota] truncating log before retry $ATTEMPT (preserving preamble)"
    : > /tmp/pivota-dev.log
    docker compose down -v --remove-orphans 2>&1 || true
  fi
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
